config/routes.rb
Rails.application.routes.draw do
  root 'teams#league'

  get 'league/' => 'teams#league'

  get 'eastern/' => 'teams#eastern_conf'

  get 'western/' => 'teams#western_conf'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/team.rb
class Team < ApplicationRecord

  scope :eastern, -> { where(conference: "Eastern")}
  scope :western, -> { where(conference: "Western")}
  scope :ranked, -> {order(wins: :desc, losses: :asc)}

def win_percent
  (wins.to_f / (wins + losses.to_f))
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def league
    @teams = Team.all.ranked

  def eastern_conf
    @teams = Team.eastern.ranked
  end

  def western_conf
    @teams = Team.western.ranked
  end

end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NbaStandings</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path%>">League Standings</a>
    </div>

    <div>
      <ul class="nav navbar-nav">
        <li><a href="<%= eastern_path %>">Eastern Conference</a></li>
        <li><a href="<%= western_path %>">Western Conference</a></li>
      </ul>
    </div>
  </div>
</nav>